BEGIN TRANSACTION;

--create temporary tables and drop old tables
CREATE TEMPORARY TABLE soa_deliver.fact_metrics_temp as
select * from soa_deliver.fact_metrics;
drop table soa_deliver.fact_metrics;

CREATE TEMPORARY TABLE soa_deliver.fact_metrics_agg_entity_temp as
select * from soa_deliver.fact_metrics_agg_entity;
drop table soa_deliver.fact_metrics_agg_entity;

CREATE TEMPORARY TABLE soa_deliver.fact_metrics_agg_district_temp as
select * from soa_deliver.fact_metrics_agg_district;
drop table soa_deliver.fact_metrics_agg_district;

CREATE TEMPORARY TABLE soa_deliver.fact_metrics_agg_zone_temp as
select * from soa_deliver.fact_metrics_agg_zone;
drop table soa_deliver.fact_metrics_agg_zone;

CREATE TEMPORARY TABLE soa_deliver.fact_metrics_agg_region_temp as
select * from soa_deliver.fact_metrics_agg_region;
drop table soa_deliver.fact_metrics_agg_region;

CREATE TEMPORARY TABLE soa_deliver.fact_metrics_agg_division_temp as
select * from soa_deliver.fact_metrics_agg_division;
drop table soa_deliver.fact_metrics_agg_division;


--create new tables
CREATE TABLE IF NOT EXISTS soa_deliver.fact_metrics
(
  cadence                                         VARCHAR(8000),
  entity                                          VARCHAR(8000),
  calendar_date                                   DATE,

  -- monthly_prerolled_12mo
  msr                                             NUMERIC,
  msr_pct                                         NUMERIC,

  -- monthly
  -- nwc_target                                      NUMERIC,
  tech_training_pct_attainment_target             NUMERIC,
  min_tr_techs                                    NUMERIC,
  nbr_fully_tr_techs                              NUMERIC,
  credit_taken                                    NUMERIC,
  credit_req                                      NUMERIC,
  saf_new_accruals                                NUMERIC,                                
  saf_new_expired                                 NUMERIC,
  saf_new_utilization                             NUMERIC,
  saf_ps_accruals                                 NUMERIC,
  saf_ps_expired                                  NUMERIC,
  saf_ps_utilization                              NUMERIC,
  saf_flex_accruals                               NUMERIC,
  saf_flex_expired                                NUMERIC,
  saf_flex_utilization                            NUMERIC,
  saf_total_accruals                              NUMERIC,
  saf_total_expired                               NUMERIC,
  saf_total_utilization                           NUMERIC,
  saf_care_connect_spend                          NUMERIC,

  -- monthly_prerolled_ytd
  profitability                                   NUMERIC,
  gp_puvr                                         NUMERIC,
  op_new_veh                                      NUMERIC,
  op_used_veh                                     NUMERIC,
  op_service                                      NUMERIC,
  op_pa_dep                                       NUMERIC,
  op_body_shop                                    NUMERIC,
  fixed_absorption                                NUMERIC,
  cust_effective_lr_subaru                        NUMERIC,
  cust_effective_lr_other                         NUMERIC,
  subaru_cust_labor_ro                            NUMERIC,
  subaru_cust_labor_sls                           NUMERIC,
  subaru_cust_labor_gp                            NUMERIC,
  subaru_cust_labor_gp_pct                        NUMERIC,
  subaru_warr_labor_ro                            NUMERIC,
  subaru_warr_labor_sls                           NUMERIC,
  subaru_warr_labor_gp                            NUMERIC,
  subaru_warr_labor_gp_pct                        NUMERIC,
  subaru_int_labor_ro                             NUMERIC,
  subaru_int_labor_sls                            NUMERIC,
  subaru_int_labor_gp                             NUMERIC,
  subaru_int_labor_gp_pct                         NUMERIC,
  subaru_prep_maint_ro                            NUMERIC,
  subaru_prep_maint_sls                           NUMERIC,
  subaru_prep_maint_gp                            NUMERIC,
  subaru_prep_maint_gp_pct                        NUMERIC,
  subaru_srv_labor_ro                             NUMERIC,
  subaru_srv_labor_sls                            NUMERIC,
  subaru_srv_labor_gp                             NUMERIC,
  subaru_srv_labor_gp_pct                         NUMERIC,
  subaru_expsrv_labor_ro                          NUMERIC,
  subaru_expsrv_labor_sls                         NUMERIC,
  subaru_expsrv_labor_gp                          NUMERIC,
  subaru_expsrv_labor_gp_pct                      NUMERIC,
  total_subaru_srv_labor_ro                       NUMERIC,
  total_subaru_srv_labor_sls                      NUMERIC,
  total_subaru_srv_labor_gp                       NUMERIC,
  total_subaru_srv_labor_gp_pct                   NUMERIC,
  subaru_parts_cust_mech_sls                      NUMERIC,
  subaru_parts_cust_mech_gp                       NUMERIC,
  subaru_parts_cust_mech_gp_pct                   NUMERIC,
  subaru_parts_cust_body_sls                      NUMERIC,
  subaru_parts_cust_body_gp                       NUMERIC,
  subaru_parts_cust_body_gp_pct                   NUMERIC,
  subaru_parts_warr_sls                           NUMERIC,
  subaru_parts_warr_gp                            NUMERIC,
  subaru_parts_warr_gp_pct                        NUMERIC,
  subaru_counter_ct                               NUMERIC,
  subaru_counter_sls                              NUMERIC,
  subaru_counter_gp                               NUMERIC,
  subaru_counter_gp_pct                           NUMERIC,
  subaru_wholesale_ct                             NUMERIC,
  subaru_wholesale_sls                            NUMERIC,
  subaru_wholesale_gp                             NUMERIC,
  subaru_wholesale_gp_pct                         NUMERIC,
  subaru_parts_prep_maint_sls                     NUMERIC,
  subaru_parts_prep_maint_gp                      NUMERIC,
  subaru_parts_prep_maint_gp_pct                  NUMERIC,
  suba_pa_sls                                     NUMERIC,
  suba_pa_gp                                      NUMERIC,
  suba_pa_gp_pct                                  NUMERIC,
  suba_pa_exp_sls                                 NUMERIC,
  suba_pa_exp_gp                                  NUMERIC,
  suba_pa_exp_gp_pct                              NUMERIC,
  tota_subaru_pa_sls                              NUMERIC,
  tota_subaru_pa_gp                               NUMERIC,
  tota_subaru_pa_gp_pct                           NUMERIC,
  labor_per_ro_subaru                             NUMERIC,
  parts_labor_sales_ratio                         NUMERIC,

  --noncompute_12mo metric
  uio_entity                                      NUMERIC,
  uio_district                                    NUMERIC,
  uio_zone                                        NUMERIC,
  uio_region                                      NUMERIC,
  uio_division                                    NUMERIC,

  --noncomputate_qtd metrics
  purchase_return_cnt_entity                      NUMERIC,
  purchase_return_cnt_district                    NUMERIC,
  purchase_return_cnt_zone                        NUMERIC,
  purchase_return_cnt_region                      NUMERIC,
  purchase_return_cnt_division                    NUMERIC,

  purchase_sat_score_entity                       NUMERIC,
  purchase_sat_score_district                     NUMERIC,
  purchase_sat_score_zone                         NUMERIC,
  purchase_sat_score_region                       NUMERIC,
  purchase_sat_score_division                     NUMERIC,

  sales_facility_score_entity                     NUMERIC,
  sales_facility_score_district                   NUMERIC,
  sales_facility_score_zone                       NUMERIC,
  sales_facility_score_region                     NUMERIC,
  sales_facility_score_division                   NUMERIC,

  sales_consultant_score_entity                   NUMERIC,
  sales_consultant_score_district                 NUMERIC,
  sales_consultant_score_zone                     NUMERIC,
  sales_consultant_score_region                   NUMERIC,
  sales_consultant_score_division                 NUMERIC,

  purchase_process_score_entity                   NUMERIC,
  purchase_process_score_district                 NUMERIC,
  purchase_process_score_zone                     NUMERIC,
  purchase_process_score_region                   NUMERIC,
  purchase_process_score_division                 NUMERIC,

  vehicle_delivery_score_entity                   NUMERIC,
  vehicle_delivery_score_district                 NUMERIC,
  vehicle_delivery_score_zone                     NUMERIC,
  vehicle_delivery_score_region                   NUMERIC,
  vehicle_delivery_score_division                 NUMERIC,

  service_return_cnt_entity                       NUMERIC,
  service_return_cnt_district                     NUMERIC,
  service_return_cnt_zone                         NUMERIC,
  service_return_cnt_region                       NUMERIC,
  service_return_cnt_division                     NUMERIC,

  service_sat_score_entity                        NUMERIC,
  service_sat_score_district                      NUMERIC,
  service_sat_score_zone                          NUMERIC,
  service_sat_score_region                        NUMERIC,
  service_sat_score_division                      NUMERIC,

  service_appt_dropoff_score_entity               NUMERIC,
  service_appt_dropoff_score_district             NUMERIC,
  service_appt_dropoff_score_zone                 NUMERIC,
  service_appt_dropoff_score_region               NUMERIC,
  service_appt_dropoff_score_division             NUMERIC,

  service_rep_score_entity                        NUMERIC,
  service_rep_score_district                      NUMERIC,
  service_rep_score_zone                          NUMERIC,
  service_rep_score_region                        NUMERIC,
  service_rep_score_division                      NUMERIC,

  service_facility_score_entity                   NUMERIC,
  service_facility_score_district                 NUMERIC,
  service_facility_score_zone                     NUMERIC,
  service_facility_score_region                   NUMERIC,
  service_facility_score_division                 NUMERIC,

  vehicle_pickup_process_score_entity             NUMERIC,
  vehicle_pickup_process_score_district           NUMERIC,
  vehicle_pickup_process_score_zone               NUMERIC,
  vehicle_pickup_process_score_region             NUMERIC,
  vehicle_pickup_process_score_division           NUMERIC,

  service_quality_score_entity                    NUMERIC,
  service_quality_score_district                  NUMERIC,
  service_quality_score_zone                      NUMERIC,
  service_quality_score_region                    NUMERIC,
  service_quality_score_division                  NUMERIC,

  frft_return_cnt_entity                          NUMERIC,
  frft_return_cnt_district                        NUMERIC,
  frft_return_cnt_zone                            NUMERIC,
  frft_return_cnt_region                          NUMERIC,
  frft_return_cnt_division                        NUMERIC,

  frft_pct_yes_score_entity                       NUMERIC,
  frft_pct_yes_score_district                     NUMERIC,
  frft_pct_yes_score_zone                         NUMERIC,
  frft_pct_yes_score_region                       NUMERIC,
  frft_pct_yes_score_division                     NUMERIC,

  frft_pct_routine_maint_yes_score_entity         NUMERIC,
  frft_pct_routine_maint_yes_score_district       NUMERIC,
  frft_pct_routine_maint_yes_score_zone           NUMERIC,
  frft_pct_routine_maint_yes_score_region         NUMERIC,
  frft_pct_routine_maint_yes_score_division       NUMERIC,

  frft_pct_warranty_yes_score_entity              NUMERIC,
  frft_pct_warranty_yes_score_district            NUMERIC,
  frft_pct_warranty_yes_score_zone                NUMERIC,
  frft_pct_warranty_yes_score_region              NUMERIC,
  frft_pct_warranty_yes_score_division            NUMERIC,

  --non_computational_mtd metrics
  part_sales_entity                               NUMERIC,
  part_sales_district                             NUMERIC,
  part_sales_zone                                 NUMERIC,
  part_sales_region                               NUMERIC,
  part_sales_division                             NUMERIC,

  part_sales_obj_entity                           NUMERIC,
  part_sales_obj_district                         NUMERIC,
  part_sales_obj_zone                             NUMERIC,
  part_sales_obj_region                           NUMERIC,
  part_sales_obj_division                         NUMERIC,

  pct_part_sales_to_obj_entity                    NUMERIC,
  pct_part_sales_to_obj_district                  NUMERIC,
  pct_part_sales_to_obj_zone                      NUMERIC,
  pct_part_sales_to_obj_region                    NUMERIC,
  pct_part_sales_to_obj_division                  NUMERIC,

  sales_rate_entity                               NUMERIC,
  sales_rate_district                             NUMERIC,
  sales_rate_zone                                 NUMERIC,
  sales_rate_region                               NUMERIC,
  sales_rate_division                             NUMERIC,

  projected_sales_entity                          NUMERIC,
  projected_sales_district                        NUMERIC,
  projected_sales_zone                            NUMERIC,
  projected_sales_region                          NUMERIC,
  projected_sales_division                        NUMERIC,

  pct_proj_vs_obj_entity                          NUMERIC,
  pct_proj_vs_obj_district                        NUMERIC,
  pct_proj_vs_obj_zone                            NUMERIC,
  pct_proj_vs_obj_region                          NUMERIC,
  pct_proj_vs_obj_division                        NUMERIC,

  port_sales_entity                               NUMERIC,
  port_sales_district                             NUMERIC,
  port_sales_zone                                 NUMERIC,
  port_sales_region                               NUMERIC,
  port_sales_division                             NUMERIC,

  port_pnvw_entity                                NUMERIC,
  port_pnvw_district                              NUMERIC,
  port_pnvw_zone                                  NUMERIC,
  port_pnvw_region                                NUMERIC,
  port_pnvw_division                              NUMERIC,

  port_obj_entity                                 NUMERIC,
  port_obj_district                               NUMERIC,
  port_obj_zone                                   NUMERIC,
  port_obj_region                                 NUMERIC,
  port_obj_division                               NUMERIC,

  port_obj_pct_entity                             NUMERIC,
  port_obj_pct_district                           NUMERIC,
  port_obj_pct_zone                               NUMERIC,
  port_obj_pct_region                             NUMERIC,
  port_obj_pct_division                           NUMERIC,

  whs_sales_entity                                NUMERIC,
  whs_sales_district                              NUMERIC,
  whs_sales_zone                                  NUMERIC,
  whs_sales_region                                NUMERIC,
  whs_sales_division                              NUMERIC,

  whs_pnvw_entity                                 NUMERIC,
  whs_pnvw_district                               NUMERIC,
  whs_pnvw_zone                                   NUMERIC,
  whs_pnvw_region                                 NUMERIC,
  whs_pnvw_division                               NUMERIC,

  whs_obj_entity                                  NUMERIC,
  whs_obj_district                                NUMERIC,
  whs_obj_zone                                    NUMERIC,
  whs_obj_region                                  NUMERIC,
  whs_obj_division                                NUMERIC,

  whs_obj_pct_entity                              NUMERIC,
  whs_obj_pct_district                            NUMERIC,
  whs_obj_pct_zone                                NUMERIC,
  whs_obj_pct_region                              NUMERIC,
  whs_obj_pct_division                            NUMERIC,

  total_sales_entity                              NUMERIC,
  total_sales_district                            NUMERIC,
  total_sales_zone                                NUMERIC,
  total_sales_region                              NUMERIC,
  total_sales_division                            NUMERIC,

  total_veh_entity                                NUMERIC,
  total_veh_district                              NUMERIC,
  total_veh_zone                                  NUMERIC,
  total_veh_region                                NUMERIC,
  total_veh_division                              NUMERIC,

  pnvw_entity                                     NUMERIC,
  pnvw_district                                   NUMERIC,
  pnvw_zone                                       NUMERIC,
  pnvw_region                                     NUMERIC,
  pnvw_division                                   NUMERIC,

  total_obj_entity                                NUMERIC,
  total_obj_district                              NUMERIC,
  total_obj_zone                                  NUMERIC,
  total_obj_region                                NUMERIC,
  total_obj_division                              NUMERIC,

  total_obj_pct_entity                            NUMERIC,
  total_obj_pct_district                          NUMERIC,
  total_obj_pct_zone                              NUMERIC,
  total_obj_pct_region                            NUMERIC,
  total_obj_pct_division                          NUMERIC,

  total_penetration_pct_entity                    NUMERIC,
  total_penetration_pct_district                  NUMERIC,
  total_penetration_pct_zone                      NUMERIC,
  total_penetration_pct_region                    NUMERIC,
  total_penetration_pct_division                  NUMERIC,

  suggested_lines_entity                          NUMERIC,
  suggested_lines_district                        NUMERIC,
  suggested_lines_zone                            NUMERIC,
  suggested_lines_region                          NUMERIC,
  suggested_lines_division                        NUMERIC,

  accepted_lines_entity                           NUMERIC,
  accepted_lines_district                         NUMERIC,
  accepted_lines_zone                             NUMERIC,
  accepted_lines_region                           NUMERIC,
  accepted_lines_division                         NUMERIC,

  line_utilization_pct_entity                     NUMERIC,
  line_utilization_pct_district                   NUMERIC,
  line_utilization_pct_zone                       NUMERIC,
  line_utilization_pct_region                     NUMERIC,
  line_utilization_pct_division                   NUMERIC,

  suggested_part_no_entity                        NUMERIC,
  suggested_part_no_district                      NUMERIC,
  suggested_part_no_zone                          NUMERIC,
  suggested_part_no_region                        NUMERIC,
  suggested_part_no_division                      NUMERIC,

  override_part_no_entity                         NUMERIC,
  override_part_no_district                       NUMERIC,
  override_part_no_zone                           NUMERIC,
  override_part_no_region                         NUMERIC,
  override_part_no_division                       NUMERIC,

  parts_accepted_pct_entity                       NUMERIC,
  parts_accepted_pct_district                     NUMERIC,
  parts_accepted_pct_zone                         NUMERIC,
  parts_accepted_pct_region                       NUMERIC,
  parts_accepted_pct_division                     NUMERIC,

  net_utilization_pct_entity                      NUMERIC,
  net_utilization_pct_district                    NUMERIC,
  net_utilization_pct_zone                        NUMERIC,
  net_utilization_pct_region                      NUMERIC,
  net_utilization_pct_division                    NUMERIC,

  total_on_hand_value_entity                      NUMERIC,
  total_on_hand_value_district                    NUMERIC,
  total_on_hand_value_zone                        NUMERIC,
  total_on_hand_value_region                      NUMERIC,
  total_on_hand_value_division                    NUMERIC,

  suggested_on_hand_value_entity                  NUMERIC,
  suggested_on_hand_value_district                NUMERIC,
  suggested_on_hand_value_zone                    NUMERIC,
  suggested_on_hand_value_region                  NUMERIC,
  suggested_on_hand_value_division                NUMERIC,

  suggested_inventory_pct_entity                  NUMERIC,
  suggested_inventory_pct_district                NUMERIC,
  suggested_inventory_pct_zone                    NUMERIC,
  suggested_inventory_pct_region                  NUMERIC,
  suggested_inventory_pct_division                NUMERIC,

  overall_performance_entity                      NUMERIC,
  overall_performance_district                    NUMERIC,
  overall_performance_zone                        NUMERIC,
  overall_performance_region                      NUMERIC,
  overall_performance_division                    NUMERIC,

  overall_rating_entity                           NUMERIC,
  overall_rating_district                         NUMERIC,
  overall_rating_zone                             NUMERIC,
  overall_rating_region                           NUMERIC,
  overall_rating_division                         NUMERIC,

  total_partseye_stock_order_value_entity         NUMERIC,
  total_partseye_stock_order_value_district       NUMERIC,
  total_partseye_stock_order_value_zone           NUMERIC,
  total_partseye_stock_order_value_region         NUMERIC,
  total_partseye_stock_order_value_division       NUMERIC,

  total_supplemental_stock_order_value_entity     NUMERIC,
  total_supplemental_stock_order_value_district   NUMERIC,
  total_supplemental_stock_order_value_zone       NUMERIC,
  total_supplemental_stock_order_value_region     NUMERIC,
  total_supplemental_stock_order_value_division   NUMERIC,

  total_emergency_order_value_entity              NUMERIC,
  total_emergency_order_value_district            NUMERIC,
  total_emergency_order_value_zone                NUMERIC,
  total_emergency_order_value_region              NUMERIC,
  total_emergency_order_value_division            NUMERIC,

  total_other_order_value_entity                  NUMERIC,
  total_other_order_value_district                NUMERIC,
  total_other_order_value_zone                    NUMERIC,
  total_other_order_value_region                  NUMERIC,
  total_other_order_value_division                NUMERIC,

  partseye_stockorder_pct_entity                  NUMERIC,
  partseye_stockorder_pct_district                NUMERIC,
  partseye_stockorder_pct_zone                    NUMERIC,
  partseye_stockorder_pct_region                  NUMERIC,
  partseye_stockorder_pct_division                NUMERIC,

  mechanical_off_shelf_fill_rate_entity           NUMERIC,
  mechanical_off_shelf_fill_rate_district         NUMERIC,
  mechanical_off_shelf_fill_rate_zone             NUMERIC,
  mechanical_off_shelf_fill_rate_region           NUMERIC,
  mechanical_off_shelf_fill_rate_division         NUMERIC,

  mechanical_pieces_sold_entity                   NUMERIC,
  mechanical_pieces_sold_district                 NUMERIC,
  mechanical_pieces_sold_zone                     NUMERIC,
  mechanical_pieces_sold_region                   NUMERIC,
  mechanical_pieces_sold_division                 NUMERIC,

  mechanical_pieces_sold_from_shelf_entity        NUMERIC,
  mechanical_pieces_sold_from_shelf_district      NUMERIC,
  mechanical_pieces_sold_from_shelf_zone          NUMERIC,
  mechanical_pieces_sold_from_shelf_region        NUMERIC,
  mechanical_pieces_sold_from_shelf_division      NUMERIC,

  mechanical_emergency_orders_entity              NUMERIC,
  mechanical_emergency_orders_district            NUMERIC,
  mechanical_emergency_orders_zone                NUMERIC,
  mechanical_emergency_orders_region              NUMERIC,
  mechanical_emergency_orders_division            NUMERIC,

  mechanical_lost_sales_entity                    NUMERIC,
  mechanical_lost_sales_district                  NUMERIC,
  mechanical_lost_sales_zone                      NUMERIC,
  mechanical_lost_sales_region                    NUMERIC,
  mechanical_lost_sales_division                  NUMERIC,

  net_off_shelf_fill_rate_pct_entity              NUMERIC,
  net_off_shelf_fill_rate_pct_district            NUMERIC,
  net_off_shelf_fill_rate_pct_zone                NUMERIC,
  net_off_shelf_fill_rate_pct_region              NUMERIC,
  net_off_shelf_fill_rate_pct_division            NUMERIC,

  total_off_shelf_fill_rate_entity                NUMERIC,
  total_off_shelf_fill_rate_district              NUMERIC,
  total_off_shelf_fill_rate_zone                  NUMERIC,
  total_off_shelf_fill_rate_region                NUMERIC,
  total_off_shelf_fill_rate_division              NUMERIC,

  lost_sales_part_pct_entity                      NUMERIC,
  lost_sales_part_pct_district                    NUMERIC,
  lost_sales_part_pct_zone                        NUMERIC,
  lost_sales_part_pct_region                      NUMERIC,
  lost_sales_part_pct_division                    NUMERIC,

  lost_sales_total_entity                         NUMERIC,
  lost_sales_total_district                       NUMERIC,
  lost_sales_total_zone                           NUMERIC,
  lost_sales_total_region                         NUMERIC,
  lost_sales_total_division                       NUMERIC,

  total_demand_entity                             NUMERIC,
  total_demand_district                           NUMERIC,
  total_demand_zone                               NUMERIC,
  total_demand_region                             NUMERIC,
  total_demand_division                           NUMERIC,

  total_demand_per_employee_3_entity              NUMERIC,
  total_demand_per_employee_3_district            NUMERIC,
  total_demand_per_employee_3_zone                NUMERIC,
  total_demand_per_employee_3_region              NUMERIC,
  total_demand_per_employee_3_division            NUMERIC,

  total_suggestible_demand_entity                 NUMERIC,
  total_suggestible_demand_district               NUMERIC,
  total_suggestible_demand_zone                   NUMERIC,
  total_suggestible_demand_region                 NUMERIC,
  total_suggestible_demand_division               NUMERIC,

  vehicle_sales_entity                            NUMERIC,
  vehicle_sales_district                          NUMERIC,
  vehicle_sales_zone                              NUMERIC,
  vehicle_sales_region                            NUMERIC,
  vehicle_sales_division                          NUMERIC,

  mechanical_sales_entity                         NUMERIC,
  mechanical_sales_district                       NUMERIC,
  mechanical_sales_zone                           NUMERIC,
  mechanical_sales_region                         NUMERIC,
  mechanical_sales_division                       NUMERIC,

  maintenance_sales_entity                        NUMERIC,
  maintenance_sales_district                      NUMERIC,
  maintenance_sales_zone                          NUMERIC,
  maintenance_sales_region                        NUMERIC,
  maintenance_sales_division                      NUMERIC,

  cpo_sales_entity                                NUMERIC,
  cpo_sales_district                              NUMERIC,
  cpo_sales_zone                                  NUMERIC,
  cpo_sales_region                                NUMERIC,
  cpo_sales_division                              NUMERIC,

  total_sales_security_entity                     NUMERIC,
  total_sales_security_district                   NUMERIC,
  total_sales_security_zone                       NUMERIC,
  total_sales_security_region                     NUMERIC,
  total_sales_security_division                   NUMERIC,

  mechanical_penetration_pct_entity               NUMERIC,
  mechanical_penetration_pct_district             NUMERIC,
  mechanical_penetration_pct_zone                 NUMERIC,
  mechanical_penetration_pct_region               NUMERIC,
  mechanical_penetration_pct_division             NUMERIC,

  maintenance_penetration_pct_entity              NUMERIC,
  maintenance_penetration_pct_district            NUMERIC,
  maintenance_penetration_pct_zone                NUMERIC,
  maintenance_penetration_pct_region              NUMERIC,
  maintenance_penetration_pct_division            NUMERIC,

  cpo_penetration_pct_entity                      NUMERIC,
  cpo_penetration_pct_district                    NUMERIC,
  cpo_penetration_pct_zone                        NUMERIC,
  cpo_penetration_pct_region                      NUMERIC,
  cpo_penetration_pct_division                    NUMERIC,

  mech_cpo_pen_pct_entity                         NUMERIC,
  mech_cpo_pen_pct_district                       NUMERIC,
  mech_cpo_pen_pct_zone                           NUMERIC,
  mech_cpo_pen_pct_region                         NUMERIC,
  mech_cpo_pen_pct_division                       NUMERIC,

  mech_cpo_pen_pct_obj_entity                     NUMERIC,
  mech_cpo_pen_pct_obj_district                   NUMERIC,
  mech_cpo_pen_pct_obj_zone                       NUMERIC,
  mech_cpo_pen_pct_obj_region                     NUMERIC,
  mech_cpo_pen_pct_obj_division                   NUMERIC,

  msr_last_update                                 DATE,
  msr_pct_last_update                             DATE,
  uio_last_update                                 DATE,
  nwc_target_last_update                          DATE,
  tech_training_pct_attainment_target_last_update DATE,
  fully_trained_techs_req_last_update             DATE,
  fully_trained_techs_last_update                 DATE,
  tech_training_credit_taken_last_update          DATE,
  tech_training_credit_req_last_update            DATE,
  purchase_return_cnt_last_update                 DATE,
  purchase_sat_score_last_update                  DATE,
  sales_facility_score_last_update                DATE,
  sales_consultant_score_last_update              DATE,
  purchase_process_score_last_update              DATE,
  vehicle_delivery_score_last_update              DATE,
  service_return_cnt_last_update                  DATE,
  service_sat_score_last_update                   DATE,
  service_appt_dropoff_score_last_update          DATE,
  service_rep_score_last_update                   DATE,
  service_facility_score_last_update              DATE,
  vehicle_pickup_process_score_last_update        DATE,
  service_quality_score_last_update               DATE,
  frft_return_cnt_last_update                     DATE,
  frft_pct_yes_score_last_update                  DATE,
  frft_pct_routine_maint_yes_score_last_update    DATE,
  frft_pct_warranty_yes_score_last_update         DATE,
  part_sales_last_update                          DATE,
  part_sales_obj_last_update                      DATE,
  pct_part_sales_to_obj_last_update               DATE,
  sales_rate_last_update                          DATE,
  projected_sales_last_update                     DATE,
  pct_proj_vs_obj_last_update                     DATE,

  port_sales_last_update                          DATE,
  port_pnvw_last_update                           DATE,
  port_obj_last_update                            DATE,
  port_obj_pct_last_update                        DATE,
  whs_sales_last_update                           DATE,
  whs_pnvw_last_update                            DATE,
  whs_obj_last_update                             DATE,
  whs_obj_pct_last_update                         DATE,
  total_sales_last_update                         DATE,
  total_veh_last_update                           DATE,
  pnvw_last_update                                DATE,
  total_obj_last_update                           DATE,
  total_obj_pct_last_update                       DATE
);


CREATE TABLE IF NOT EXISTS soa_deliver.fact_metrics_agg_entity
(
  entity                              VARCHAR(8000),
  entity_path                         VARCHAR(8000),
  cadence                             VARCHAR(8000),
  compute_period                      VARCHAR(8000),
  period_type                         VARCHAR(8000),
  to_period                           DATE,

  msr                                 NUMERIC,
  msr_pct                             NUMERIC,
  uio                                 NUMERIC,

  -- nwc_target                          NUMERIC,

  tech_training_pct_attainment_target NUMERIC,
  fully_trained_techs_req             NUMERIC,
  fully_trained_techs                 NUMERIC,
  tech_training_credit_taken          NUMERIC,
  tech_training_credit_req            NUMERIC,
  tech_training_pct_attainment        NUMERIC,
  saf_new_accruals                    NUMERIC,                                
  saf_new_expired                     NUMERIC,
  saf_new_utilization                 NUMERIC,
  saf_ps_accruals                     NUMERIC,
  saf_ps_expired                      NUMERIC,
  saf_ps_utilization                  NUMERIC,
  saf_flex_accruals                   NUMERIC,
  saf_flex_expired                    NUMERIC,
  saf_flex_utilization                NUMERIC,
  saf_total_accruals                  NUMERIC,
  saf_total_expired                   NUMERIC,
  saf_total_utilization               NUMERIC,
  saf_care_connect_spend              NUMERIC,

  profitability                       NUMERIC,

  purchase_return_cnt                 NUMERIC,
  purchase_sat_score                  NUMERIC,
  sales_facility_score                NUMERIC,
  sales_consultant_score              NUMERIC,
  purchase_process_score              NUMERIC,
  vehicle_delivery_score              NUMERIC,
  service_return_cnt                  NUMERIC,
  service_sat_score                   NUMERIC,
  service_appt_dropoff_score          NUMERIC,
  service_rep_score                   NUMERIC,
  service_facility_score              NUMERIC,
  vehicle_pickup_process_score        NUMERIC,
  service_quality_score               NUMERIC,
  frft_return_cnt                     NUMERIC,
  frft_pct_yes_score                  NUMERIC,
  frft_pct_routine_maint_yes_score    NUMERIC,
  frft_pct_warranty_yes_score         NUMERIC,

  part_sales                          NUMERIC,
  part_sales_obj                      NUMERIC,
  pct_part_sales_to_obj               NUMERIC,
  sales_rate                          NUMERIC,
  projected_sales                     NUMERIC,
  pct_proj_vs_obj                     NUMERIC,
  port_sales                          NUMERIC,
  port_pnvw                           NUMERIC,
  port_obj                            NUMERIC,
  port_obj_pct                        NUMERIC,
  whs_sales                           NUMERIC,
  whs_pnvw                            NUMERIC,
  whs_obj                             NUMERIC,
  whs_obj_pct                         NUMERIC,
  total_sales                         NUMERIC,
  total_veh                           NUMERIC,
  pnvw                                NUMERIC,
  total_obj                           NUMERIC,
  total_obj_pct                       NUMERIC,
  total_penetration_pct               NUMERIC,
  
  suggested_lines                      NUMERIC,
  accepted_lines                       NUMERIC,
  line_utilization_pct                 NUMERIC,
  suggested_part_no                    NUMERIC,
  override_part_no                     NUMERIC,
  parts_accepted_pct                   NUMERIC,
  net_utilization_pct                  NUMERIC,
  total_on_hand_value                  NUMERIC,
  suggested_on_hand_value              NUMERIC,
  suggested_inventory_pct              NUMERIC,
  overall_performance                  NUMERIC,
  overall_rating                       NUMERIC,
  total_partseye_stock_order_value     NUMERIC,
  total_supplemental_stock_order_value NUMERIC,
  total_emergency_order_value          NUMERIC,
  total_other_order_value              NUMERIC,
  partseye_stockorder_pct              NUMERIC,
  mechanical_off_shelf_fill_rate       NUMERIC,
  mechanical_pieces_sold               NUMERIC,
  mechanical_pieces_sold_from_shelf    NUMERIC,
  mechanical_emergency_orders          NUMERIC,
  mechanical_lost_sales                NUMERIC,
  net_off_shelf_fill_rate_pct          NUMERIC,
  total_off_shelf_fill_rate            NUMERIC,
  lost_sales_part_pct                  NUMERIC,
  lost_sales_total                     NUMERIC,
  total_demand                         NUMERIC,
  total_demand_per_employee_3          NUMERIC,
  total_suggestible_demand             NUMERIC,
  vehicle_sales                       NUMERIC,
  mechanical_sales                    NUMERIC,
  maintenance_sales                   NUMERIC,
  cpo_sales                           NUMERIC,
  total_sales_security                NUMERIC,
  mechanical_penetration_pct          NUMERIC,
  maintenance_penetration_pct         NUMERIC,
  cpo_penetration_pct                 NUMERIC,
  mech_cpo_pen_pct                    NUMERIC,
  mech_cpo_pen_pct_obj                NUMERIC,
  gp_puvr                             NUMERIC,
  op_new_veh                          NUMERIC,
  op_used_veh                         NUMERIC,
  op_service                          NUMERIC,
  op_pa_dep                           NUMERIC,
  op_body_shop                        NUMERIC,
  fixed_absorption                    NUMERIC,
  cust_effective_lr_subaru            NUMERIC,
  cust_effective_lr_other             NUMERIC,
  subaru_cust_labor_ro                NUMERIC,
  subaru_cust_labor_sls               NUMERIC,
  subaru_cust_labor_gp                NUMERIC,
  subaru_cust_labor_gp_pct            NUMERIC,
  subaru_warr_labor_ro                NUMERIC,
  subaru_warr_labor_sls               NUMERIC,
  subaru_warr_labor_gp                NUMERIC,
  subaru_warr_labor_gp_pct            NUMERIC,
  subaru_int_labor_ro                 NUMERIC,
  subaru_int_labor_sls                NUMERIC,
  subaru_int_labor_gp                 NUMERIC,
  subaru_int_labor_gp_pct             NUMERIC,
  subaru_prep_maint_ro                NUMERIC,
  subaru_prep_maint_sls               NUMERIC,
  subaru_prep_maint_gp                NUMERIC,
  subaru_prep_maint_gp_pct            NUMERIC,
  subaru_srv_labor_ro                 NUMERIC,
  subaru_srv_labor_sls                NUMERIC,
  subaru_srv_labor_gp                 NUMERIC,
  subaru_srv_labor_gp_pct             NUMERIC,
  subaru_expsrv_labor_ro              NUMERIC,
  subaru_expsrv_labor_sls             NUMERIC,
  subaru_expsrv_labor_gp              NUMERIC,
  subaru_expsrv_labor_gp_pct          NUMERIC,
  total_subaru_srv_labor_ro           NUMERIC,
  total_subaru_srv_labor_sls          NUMERIC,
  total_subaru_srv_labor_gp           NUMERIC,
  total_subaru_srv_labor_gp_pct       NUMERIC,
  subaru_parts_cust_mech_sls          NUMERIC,
  subaru_parts_cust_mech_gp           NUMERIC,
  subaru_parts_cust_mech_gp_pct       NUMERIC,
  subaru_parts_cust_body_sls          NUMERIC,
  subaru_parts_cust_body_gp           NUMERIC,
  subaru_parts_cust_body_gp_pct       NUMERIC,
  subaru_parts_warr_sls               NUMERIC,
  subaru_parts_warr_gp                NUMERIC,
  subaru_parts_warr_gp_pct            NUMERIC,
  subaru_counter_ct                   NUMERIC,
  subaru_counter_sls                  NUMERIC,
  subaru_counter_gp                   NUMERIC,
  subaru_counter_gp_pct               NUMERIC,
  subaru_wholesale_ct                 NUMERIC,
  subaru_wholesale_sls                NUMERIC,
  subaru_wholesale_gp                 NUMERIC,
  subaru_wholesale_gp_pct             NUMERIC,
  subaru_parts_prep_maint_sls         NUMERIC,
  subaru_parts_prep_maint_gp          NUMERIC,
  subaru_parts_prep_maint_gp_pct      NUMERIC,
  suba_pa_sls                         NUMERIC,
  suba_pa_gp                          NUMERIC,
  suba_pa_gp_pct                      NUMERIC,
  suba_pa_exp_sls                     NUMERIC,
  suba_pa_exp_gp                      NUMERIC,
  suba_pa_exp_gp_pct                  NUMERIC,
  tota_subaru_pa_sls                  NUMERIC,
  tota_subaru_pa_gp                   NUMERIC,
  tota_subaru_pa_gp_pct               NUMERIC,
  labor_per_ro_subaru                 NUMERIC,
  parts_labor_sales_ratio             NUMERIC
);

CREATE TABLE IF NOT EXISTS soa_deliver.fact_metrics_agg_district
(
  district                             VARCHAR(8000),
  district_path                        VARCHAR(8000),
  cadence                              VARCHAR(8000),
  compute_period                       VARCHAR(8000),
  period_type                          VARCHAR(8000),
  to_period                            DATE,

  msr                                 NUMERIC,
  msr_pct                             NUMERIC,
  uio                                 NUMERIC,

  -- nwc_target                          NUMERIC,

  tech_training_pct_attainment_target NUMERIC,
  fully_trained_techs_req             NUMERIC,
  fully_trained_techs                 NUMERIC,
  tech_training_credit_taken          NUMERIC,
  tech_training_credit_req            NUMERIC,
  tech_training_pct_attainment        NUMERIC,
  saf_new_accruals                    NUMERIC,                                
  saf_new_expired                     NUMERIC,
  saf_new_utilization                 NUMERIC,
  saf_ps_accruals                     NUMERIC,
  saf_ps_expired                      NUMERIC,
  saf_ps_utilization                  NUMERIC,
  saf_flex_accruals                   NUMERIC,
  saf_flex_expired                    NUMERIC,
  saf_flex_utilization                NUMERIC,
  saf_total_accruals                  NUMERIC,
  saf_total_expired                   NUMERIC,
  saf_total_utilization               NUMERIC,
  saf_care_connect_spend              NUMERIC,
  profitability                       NUMERIC,

  purchase_return_cnt                 NUMERIC,
  purchase_sat_score                  NUMERIC,
  sales_facility_score                NUMERIC,
  sales_consultant_score              NUMERIC,
  purchase_process_score              NUMERIC,
  vehicle_delivery_score              NUMERIC,
  service_return_cnt                  NUMERIC,
  service_sat_score                   NUMERIC,
  service_appt_dropoff_score          NUMERIC,
  service_rep_score                   NUMERIC,
  service_facility_score              NUMERIC,
  vehicle_pickup_process_score        NUMERIC,
  service_quality_score               NUMERIC,
  frft_return_cnt                     NUMERIC,
  frft_pct_yes_score                  NUMERIC,
  frft_pct_routine_maint_yes_score    NUMERIC,
  frft_pct_warranty_yes_score         NUMERIC,

  part_sales                          NUMERIC,
  part_sales_obj                      NUMERIC,
  pct_part_sales_to_obj               NUMERIC,
  sales_rate                          NUMERIC,
  projected_sales                     NUMERIC,
  pct_proj_vs_obj                     NUMERIC,
  port_sales                          NUMERIC,
  port_pnvw                           NUMERIC,
  port_obj                            NUMERIC,
  port_obj_pct                        NUMERIC,
  whs_sales                           NUMERIC,
  whs_pnvw                            NUMERIC,
  whs_obj                             NUMERIC,
  whs_obj_pct                         NUMERIC,
  total_sales                         NUMERIC,
  total_veh                           NUMERIC,
  pnvw                                NUMERIC,
  total_obj                           NUMERIC,
  total_obj_pct                       NUMERIC,
  total_penetration_pct               NUMERIC,
  
  suggested_lines                      NUMERIC,
  accepted_lines                       NUMERIC,
  line_utilization_pct                 NUMERIC,
  suggested_part_no                    NUMERIC,
  override_part_no                     NUMERIC,
  parts_accepted_pct                   NUMERIC,
  net_utilization_pct                  NUMERIC,
  total_on_hand_value                  NUMERIC,
  suggested_on_hand_value              NUMERIC,
  suggested_inventory_pct              NUMERIC,
  overall_performance                  NUMERIC,
  overall_rating                       NUMERIC,
  total_partseye_stock_order_value     NUMERIC,
  total_supplemental_stock_order_value NUMERIC,
  total_emergency_order_value          NUMERIC,
  total_other_order_value              NUMERIC,
  partseye_stockorder_pct              NUMERIC,
  mechanical_off_shelf_fill_rate       NUMERIC,
  mechanical_pieces_sold               NUMERIC,
  mechanical_pieces_sold_from_shelf    NUMERIC,
  mechanical_emergency_orders          NUMERIC,
  mechanical_lost_sales                NUMERIC,
  net_off_shelf_fill_rate_pct          NUMERIC,
  total_off_shelf_fill_rate            NUMERIC,
  lost_sales_part_pct                  NUMERIC,
  lost_sales_total                     NUMERIC,
  total_demand                         NUMERIC,
  total_demand_per_employee_3          NUMERIC,
  total_suggestible_demand             NUMERIC,
  vehicle_sales                       NUMERIC,
  mechanical_sales                    NUMERIC,
  maintenance_sales                   NUMERIC,
  cpo_sales                           NUMERIC,
  total_sales_security                NUMERIC,
  mechanical_penetration_pct          NUMERIC,
  maintenance_penetration_pct         NUMERIC,
  cpo_penetration_pct                 NUMERIC,
  mech_cpo_pen_pct                    NUMERIC,
  mech_cpo_pen_pct_obj                NUMERIC,
  gp_puvr                             NUMERIC,
  op_new_veh                          NUMERIC,
  op_used_veh                         NUMERIC,
  op_service                          NUMERIC,
  op_pa_dep                           NUMERIC,
  op_body_shop                        NUMERIC,
  fixed_absorption                    NUMERIC,
  cust_effective_lr_subaru            NUMERIC,
  cust_effective_lr_other             NUMERIC,
  subaru_cust_labor_ro                NUMERIC,
  subaru_cust_labor_sls               NUMERIC,
  subaru_cust_labor_gp                NUMERIC,
  subaru_cust_labor_gp_pct            NUMERIC,
  subaru_warr_labor_ro                NUMERIC,
  subaru_warr_labor_sls               NUMERIC,
  subaru_warr_labor_gp                NUMERIC,
  subaru_warr_labor_gp_pct            NUMERIC,
  subaru_int_labor_ro                 NUMERIC,
  subaru_int_labor_sls                NUMERIC,
  subaru_int_labor_gp                 NUMERIC,
  subaru_int_labor_gp_pct             NUMERIC,
  subaru_prep_maint_ro                NUMERIC,
  subaru_prep_maint_sls               NUMERIC,
  subaru_prep_maint_gp                NUMERIC,
  subaru_prep_maint_gp_pct            NUMERIC,
  subaru_srv_labor_ro                 NUMERIC,
  subaru_srv_labor_sls                NUMERIC,
  subaru_srv_labor_gp                 NUMERIC,
  subaru_srv_labor_gp_pct             NUMERIC,
  subaru_expsrv_labor_ro              NUMERIC,
  subaru_expsrv_labor_sls             NUMERIC,
  subaru_expsrv_labor_gp              NUMERIC,
  subaru_expsrv_labor_gp_pct          NUMERIC,
  total_subaru_srv_labor_ro           NUMERIC,
  total_subaru_srv_labor_sls          NUMERIC,
  total_subaru_srv_labor_gp           NUMERIC,
  total_subaru_srv_labor_gp_pct       NUMERIC,
  subaru_parts_cust_mech_sls          NUMERIC,
  subaru_parts_cust_mech_gp           NUMERIC,
  subaru_parts_cust_mech_gp_pct       NUMERIC,
  subaru_parts_cust_body_sls          NUMERIC,
  subaru_parts_cust_body_gp           NUMERIC,
  subaru_parts_cust_body_gp_pct       NUMERIC,
  subaru_parts_warr_sls               NUMERIC,
  subaru_parts_warr_gp                NUMERIC,
  subaru_parts_warr_gp_pct            NUMERIC,
  subaru_counter_ct                   NUMERIC,
  subaru_counter_sls                  NUMERIC,
  subaru_counter_gp                   NUMERIC,
  subaru_counter_gp_pct               NUMERIC,
  subaru_wholesale_ct                 NUMERIC,
  subaru_wholesale_sls                NUMERIC,
  subaru_wholesale_gp                 NUMERIC,
  subaru_wholesale_gp_pct             NUMERIC,
  subaru_parts_prep_maint_sls         NUMERIC,
  subaru_parts_prep_maint_gp          NUMERIC,
  subaru_parts_prep_maint_gp_pct      NUMERIC,
  suba_pa_sls                         NUMERIC,
  suba_pa_gp                          NUMERIC,
  suba_pa_gp_pct                      NUMERIC,
  suba_pa_exp_sls                     NUMERIC,
  suba_pa_exp_gp                      NUMERIC,
  suba_pa_exp_gp_pct                  NUMERIC,
  tota_subaru_pa_sls                  NUMERIC,
  tota_subaru_pa_gp                   NUMERIC,
  tota_subaru_pa_gp_pct               NUMERIC,
  labor_per_ro_subaru                 NUMERIC,
  parts_labor_sales_ratio             NUMERIC
);


CREATE TABLE IF NOT EXISTS soa_deliver.fact_metrics_agg_zone
(
  zone                                VARCHAR(8000),
  zone_path                           VARCHAR(8000),
  cadence                             VARCHAR(8000),
  compute_period                      VARCHAR(8000),
  period_type                         VARCHAR(8000),
  to_period                           DATE,

  msr                                 NUMERIC,
  msr_pct                             NUMERIC,
  uio                                 NUMERIC,

  -- nwc_target                          NUMERIC,

  tech_training_pct_attainment_target NUMERIC,
  fully_trained_techs_req             NUMERIC,
  fully_trained_techs                 NUMERIC,
  tech_training_credit_taken          NUMERIC,
  tech_training_credit_req            NUMERIC,
  tech_training_pct_attainment        NUMERIC,
  saf_new_accruals                    NUMERIC,                                
  saf_new_expired                     NUMERIC,
  saf_new_utilization                 NUMERIC,
  saf_ps_accruals                     NUMERIC,
  saf_ps_expired                      NUMERIC,
  saf_ps_utilization                  NUMERIC,
  saf_flex_accruals                   NUMERIC,
  saf_flex_expired                    NUMERIC,
  saf_flex_utilization                NUMERIC,
  saf_total_accruals                  NUMERIC,
  saf_total_expired                   NUMERIC,
  saf_total_utilization               NUMERIC,
  saf_care_connect_spend              NUMERIC,
  profitability                       NUMERIC,

  purchase_return_cnt                 NUMERIC,
  purchase_sat_score                  NUMERIC,
  sales_facility_score                NUMERIC,
  sales_consultant_score              NUMERIC,
  purchase_process_score              NUMERIC,
  vehicle_delivery_score              NUMERIC,
  service_return_cnt                  NUMERIC,
  service_sat_score                   NUMERIC,
  service_appt_dropoff_score          NUMERIC,
  service_rep_score                   NUMERIC,
  service_facility_score              NUMERIC,
  vehicle_pickup_process_score        NUMERIC,
  service_quality_score               NUMERIC,
  frft_return_cnt                     NUMERIC,
  frft_pct_yes_score                  NUMERIC,
  frft_pct_routine_maint_yes_score    NUMERIC,
  frft_pct_warranty_yes_score         NUMERIC,

  part_sales                          NUMERIC,
  part_sales_obj                      NUMERIC,
  pct_part_sales_to_obj               NUMERIC,
  sales_rate                          NUMERIC,
  projected_sales                     NUMERIC,
  pct_proj_vs_obj                     NUMERIC,
  port_sales                          NUMERIC,
  port_pnvw                           NUMERIC,
  port_obj                            NUMERIC,
  port_obj_pct                        NUMERIC,
  whs_sales                           NUMERIC,
  whs_pnvw                            NUMERIC,
  whs_obj                             NUMERIC,
  whs_obj_pct                         NUMERIC,
  total_sales                         NUMERIC,
  total_veh                           NUMERIC,
  pnvw                                NUMERIC,
  total_obj                           NUMERIC,
  total_obj_pct                       NUMERIC,
  total_penetration_pct               NUMERIC,
  
  suggested_lines                      NUMERIC,
  accepted_lines                       NUMERIC,
  line_utilization_pct                 NUMERIC,
  suggested_part_no                    NUMERIC,
  override_part_no                     NUMERIC,
  parts_accepted_pct                   NUMERIC,
  net_utilization_pct                  NUMERIC,
  total_on_hand_value                  NUMERIC,
  suggested_on_hand_value              NUMERIC,
  suggested_inventory_pct              NUMERIC,
  overall_performance                  NUMERIC,
  overall_rating                       NUMERIC,
  total_partseye_stock_order_value     NUMERIC,
  total_supplemental_stock_order_value NUMERIC,
  total_emergency_order_value          NUMERIC,
  total_other_order_value              NUMERIC,
  partseye_stockorder_pct              NUMERIC,
  mechanical_off_shelf_fill_rate       NUMERIC,
  mechanical_pieces_sold               NUMERIC,
  mechanical_pieces_sold_from_shelf    NUMERIC,
  mechanical_emergency_orders          NUMERIC,
  mechanical_lost_sales                NUMERIC,
  net_off_shelf_fill_rate_pct          NUMERIC,
  total_off_shelf_fill_rate            NUMERIC,
  lost_sales_part_pct                  NUMERIC,
  lost_sales_total                     NUMERIC,
  total_demand                         NUMERIC,
  total_demand_per_employee_3          NUMERIC,
  total_suggestible_demand             NUMERIC,
  vehicle_sales                       NUMERIC,
  mechanical_sales                    NUMERIC,
  maintenance_sales                   NUMERIC,
  cpo_sales                           NUMERIC,
  total_sales_security                NUMERIC,
  mechanical_penetration_pct          NUMERIC,
  maintenance_penetration_pct         NUMERIC,
  cpo_penetration_pct                 NUMERIC,
  mech_cpo_pen_pct                    NUMERIC,
  mech_cpo_pen_pct_obj                NUMERIC,
  gp_puvr                             NUMERIC,
  op_new_veh                          NUMERIC,
  op_used_veh                         NUMERIC,
  op_service                          NUMERIC,
  op_pa_dep                           NUMERIC,
  op_body_shop                        NUMERIC,
  fixed_absorption                    NUMERIC,
  cust_effective_lr_subaru            NUMERIC,
  cust_effective_lr_other             NUMERIC,
  subaru_cust_labor_ro                NUMERIC,
  subaru_cust_labor_sls               NUMERIC,
  subaru_cust_labor_gp                NUMERIC,
  subaru_cust_labor_gp_pct            NUMERIC,
  subaru_warr_labor_ro                NUMERIC,
  subaru_warr_labor_sls               NUMERIC,
  subaru_warr_labor_gp                NUMERIC,
  subaru_warr_labor_gp_pct            NUMERIC,
  subaru_int_labor_ro                 NUMERIC,
  subaru_int_labor_sls                NUMERIC,
  subaru_int_labor_gp                 NUMERIC,
  subaru_int_labor_gp_pct             NUMERIC,
  subaru_prep_maint_ro                NUMERIC,
  subaru_prep_maint_sls               NUMERIC,
  subaru_prep_maint_gp                NUMERIC,
  subaru_prep_maint_gp_pct            NUMERIC,
  subaru_srv_labor_ro                 NUMERIC,
  subaru_srv_labor_sls                NUMERIC,
  subaru_srv_labor_gp                 NUMERIC,
  subaru_srv_labor_gp_pct             NUMERIC,
  subaru_expsrv_labor_ro              NUMERIC,
  subaru_expsrv_labor_sls             NUMERIC,
  subaru_expsrv_labor_gp              NUMERIC,
  subaru_expsrv_labor_gp_pct          NUMERIC,
  total_subaru_srv_labor_ro           NUMERIC,
  total_subaru_srv_labor_sls          NUMERIC,
  total_subaru_srv_labor_gp           NUMERIC,
  total_subaru_srv_labor_gp_pct       NUMERIC,
  subaru_parts_cust_mech_sls          NUMERIC,
  subaru_parts_cust_mech_gp           NUMERIC,
  subaru_parts_cust_mech_gp_pct       NUMERIC,
  subaru_parts_cust_body_sls          NUMERIC,
  subaru_parts_cust_body_gp           NUMERIC,
  subaru_parts_cust_body_gp_pct       NUMERIC,
  subaru_parts_warr_sls               NUMERIC,
  subaru_parts_warr_gp                NUMERIC,
  subaru_parts_warr_gp_pct            NUMERIC,
  subaru_counter_ct                   NUMERIC,
  subaru_counter_sls                  NUMERIC,
  subaru_counter_gp                   NUMERIC,
  subaru_counter_gp_pct               NUMERIC,
  subaru_wholesale_ct                 NUMERIC,
  subaru_wholesale_sls                NUMERIC,
  subaru_wholesale_gp                 NUMERIC,
  subaru_wholesale_gp_pct             NUMERIC,
  subaru_parts_prep_maint_sls         NUMERIC,
  subaru_parts_prep_maint_gp          NUMERIC,
  subaru_parts_prep_maint_gp_pct      NUMERIC,
  suba_pa_sls                         NUMERIC,
  suba_pa_gp                          NUMERIC,
  suba_pa_gp_pct                      NUMERIC,
  suba_pa_exp_sls                     NUMERIC,
  suba_pa_exp_gp                      NUMERIC,
  suba_pa_exp_gp_pct                  NUMERIC,
  tota_subaru_pa_sls                  NUMERIC,
  tota_subaru_pa_gp                   NUMERIC,
  tota_subaru_pa_gp_pct               NUMERIC,
  labor_per_ro_subaru                 NUMERIC,
  parts_labor_sales_ratio             NUMERIC
);


CREATE TABLE IF NOT EXISTS soa_deliver.fact_metrics_agg_region
(
  region                              VARCHAR(8000),
  region_path                         VARCHAR(8000),
  cadence                             VARCHAR(8000),
  compute_period                      VARCHAR(8000),
  period_type                         VARCHAR(8000),
  to_period                           DATE,

  msr                                 NUMERIC,
  msr_pct                             NUMERIC,
  uio                                 NUMERIC,

  -- nwc_target                          NUMERIC,

  tech_training_pct_attainment_target NUMERIC,
  fully_trained_techs_req             NUMERIC,
  fully_trained_techs                 NUMERIC,
  tech_training_credit_taken          NUMERIC,
  tech_training_credit_req            NUMERIC,
  tech_training_pct_attainment        NUMERIC,
  saf_new_accruals                    NUMERIC,                                
  saf_new_expired                     NUMERIC,
  saf_new_utilization                 NUMERIC,
  saf_ps_accruals                     NUMERIC,
  saf_ps_expired                      NUMERIC,
  saf_ps_utilization                  NUMERIC,
  saf_flex_accruals                   NUMERIC,
  saf_flex_expired                    NUMERIC,
  saf_flex_utilization                NUMERIC,
  saf_total_accruals                  NUMERIC,
  saf_total_expired                   NUMERIC,
  saf_total_utilization               NUMERIC,
  saf_care_connect_spend              NUMERIC,
  profitability                       NUMERIC,

  purchase_return_cnt                 NUMERIC,
  purchase_sat_score                  NUMERIC,
  sales_facility_score                NUMERIC,
  sales_consultant_score              NUMERIC,
  purchase_process_score              NUMERIC,
  vehicle_delivery_score              NUMERIC,
  service_return_cnt                  NUMERIC,
  service_sat_score                   NUMERIC,
  service_appt_dropoff_score          NUMERIC,
  service_rep_score                   NUMERIC,
  service_facility_score              NUMERIC,
  vehicle_pickup_process_score        NUMERIC,
  service_quality_score               NUMERIC,
  frft_return_cnt                     NUMERIC,
  frft_pct_yes_score                  NUMERIC,
  frft_pct_routine_maint_yes_score    NUMERIC,
  frft_pct_warranty_yes_score         NUMERIC,

  part_sales                          NUMERIC,
  part_sales_obj                      NUMERIC,
  pct_part_sales_to_obj               NUMERIC,
  sales_rate                          NUMERIC,
  projected_sales                     NUMERIC,
  pct_proj_vs_obj                     NUMERIC,
  port_sales                          NUMERIC,
  port_pnvw                           NUMERIC,
  port_obj                            NUMERIC,
  port_obj_pct                        NUMERIC,
  whs_sales                           NUMERIC,
  whs_pnvw                            NUMERIC,
  whs_obj                             NUMERIC,
  whs_obj_pct                         NUMERIC,
  total_sales                         NUMERIC,
  total_veh                           NUMERIC,
  pnvw                                NUMERIC,
  total_obj                           NUMERIC,
  total_obj_pct                       NUMERIC,
  total_penetration_pct               NUMERIC,
  
  suggested_lines                      NUMERIC,
  accepted_lines                       NUMERIC,
  line_utilization_pct                 NUMERIC,
  suggested_part_no                    NUMERIC,
  override_part_no                     NUMERIC,
  parts_accepted_pct                   NUMERIC,
  net_utilization_pct                  NUMERIC,
  total_on_hand_value                  NUMERIC,
  suggested_on_hand_value              NUMERIC,
  suggested_inventory_pct              NUMERIC,
  overall_performance                  NUMERIC,
  overall_rating                       NUMERIC,
  total_partseye_stock_order_value     NUMERIC,
  total_supplemental_stock_order_value NUMERIC,
  total_emergency_order_value          NUMERIC,
  total_other_order_value              NUMERIC,
  partseye_stockorder_pct              NUMERIC,
  mechanical_off_shelf_fill_rate       NUMERIC,
  mechanical_pieces_sold               NUMERIC,
  mechanical_pieces_sold_from_shelf    NUMERIC,
  mechanical_emergency_orders          NUMERIC,
  mechanical_lost_sales                NUMERIC,
  net_off_shelf_fill_rate_pct          NUMERIC,
  total_off_shelf_fill_rate            NUMERIC,
  lost_sales_part_pct                  NUMERIC,
  lost_sales_total                     NUMERIC,
  total_demand                         NUMERIC,
  total_demand_per_employee_3          NUMERIC,
  total_suggestible_demand             NUMERIC,
  vehicle_sales                       NUMERIC,
  mechanical_sales                    NUMERIC,
  maintenance_sales                   NUMERIC,
  cpo_sales                           NUMERIC,
  total_sales_security                NUMERIC,
  mechanical_penetration_pct          NUMERIC,
  maintenance_penetration_pct         NUMERIC,
  cpo_penetration_pct                 NUMERIC,
  mech_cpo_pen_pct                    NUMERIC,
  mech_cpo_pen_pct_obj                NUMERIC,
  gp_puvr                             NUMERIC,
  op_new_veh                          NUMERIC,
  op_used_veh                         NUMERIC,
  op_service                          NUMERIC,
  op_pa_dep                           NUMERIC,
  op_body_shop                        NUMERIC,
  fixed_absorption                    NUMERIC,
  cust_effective_lr_subaru            NUMERIC,
  cust_effective_lr_other             NUMERIC,
  subaru_cust_labor_ro                NUMERIC,
  subaru_cust_labor_sls               NUMERIC,
  subaru_cust_labor_gp                NUMERIC,
  subaru_cust_labor_gp_pct            NUMERIC,
  subaru_warr_labor_ro                NUMERIC,
  subaru_warr_labor_sls               NUMERIC,
  subaru_warr_labor_gp                NUMERIC,
  subaru_warr_labor_gp_pct            NUMERIC,
  subaru_int_labor_ro                 NUMERIC,
  subaru_int_labor_sls                NUMERIC,
  subaru_int_labor_gp                 NUMERIC,
  subaru_int_labor_gp_pct             NUMERIC,
  subaru_prep_maint_ro                NUMERIC,
  subaru_prep_maint_sls               NUMERIC,
  subaru_prep_maint_gp                NUMERIC,
  subaru_prep_maint_gp_pct            NUMERIC,
  subaru_srv_labor_ro                 NUMERIC,
  subaru_srv_labor_sls                NUMERIC,
  subaru_srv_labor_gp                 NUMERIC,
  subaru_srv_labor_gp_pct             NUMERIC,
  subaru_expsrv_labor_ro              NUMERIC,
  subaru_expsrv_labor_sls             NUMERIC,
  subaru_expsrv_labor_gp              NUMERIC,
  subaru_expsrv_labor_gp_pct          NUMERIC,
  total_subaru_srv_labor_ro           NUMERIC,
  total_subaru_srv_labor_sls          NUMERIC,
  total_subaru_srv_labor_gp           NUMERIC,
  total_subaru_srv_labor_gp_pct       NUMERIC,
  subaru_parts_cust_mech_sls          NUMERIC,
  subaru_parts_cust_mech_gp           NUMERIC,
  subaru_parts_cust_mech_gp_pct       NUMERIC,
  subaru_parts_cust_body_sls          NUMERIC,
  subaru_parts_cust_body_gp           NUMERIC,
  subaru_parts_cust_body_gp_pct       NUMERIC,
  subaru_parts_warr_sls               NUMERIC,
  subaru_parts_warr_gp                NUMERIC,
  subaru_parts_warr_gp_pct            NUMERIC,
  subaru_counter_ct                   NUMERIC,
  subaru_counter_sls                  NUMERIC,
  subaru_counter_gp                   NUMERIC,
  subaru_counter_gp_pct               NUMERIC,
  subaru_wholesale_ct                 NUMERIC,
  subaru_wholesale_sls                NUMERIC,
  subaru_wholesale_gp                 NUMERIC,
  subaru_wholesale_gp_pct             NUMERIC,
  subaru_parts_prep_maint_sls         NUMERIC,
  subaru_parts_prep_maint_gp          NUMERIC,
  subaru_parts_prep_maint_gp_pct      NUMERIC,
  suba_pa_sls                         NUMERIC,
  suba_pa_gp                          NUMERIC,
  suba_pa_gp_pct                      NUMERIC,
  suba_pa_exp_sls                     NUMERIC,
  suba_pa_exp_gp                      NUMERIC,
  suba_pa_exp_gp_pct                  NUMERIC,
  tota_subaru_pa_sls                  NUMERIC,
  tota_subaru_pa_gp                   NUMERIC,
  tota_subaru_pa_gp_pct               NUMERIC,
  labor_per_ro_subaru                 NUMERIC,
  parts_labor_sales_ratio             NUMERIC
);


CREATE TABLE IF NOT EXISTS soa_deliver.fact_metrics_agg_division
(
  division                            VARCHAR(8000),
  division_path                       VARCHAR(8000),
  cadence                             VARCHAR(8000),
  compute_period                      VARCHAR(8000),
  period_type                         VARCHAR(8000),
  to_period                           DATE,

  msr                                 NUMERIC,
  msr_pct                             NUMERIC,
  uio                                 NUMERIC,

  -- nwc_target                          NUMERIC,

  tech_training_pct_attainment_target NUMERIC,
  fully_trained_techs_req             NUMERIC,
  fully_trained_techs                 NUMERIC,
  tech_training_credit_taken          NUMERIC,
  tech_training_credit_req            NUMERIC,
  tech_training_pct_attainment        NUMERIC,
  saf_new_accruals                    NUMERIC,                                
  saf_new_expired                     NUMERIC,
  saf_new_utilization                 NUMERIC,
  saf_ps_accruals                     NUMERIC,
  saf_ps_expired                      NUMERIC,
  saf_ps_utilization                  NUMERIC,
  saf_flex_accruals                   NUMERIC,
  saf_flex_expired                    NUMERIC,
  saf_flex_utilization                NUMERIC,
  saf_total_accruals                  NUMERIC,
  saf_total_expired                   NUMERIC,
  saf_total_utilization               NUMERIC,
  saf_care_connect_spend              NUMERIC,
  profitability                       NUMERIC,

  purchase_return_cnt                 NUMERIC,
  purchase_sat_score                  NUMERIC,
  sales_facility_score                NUMERIC,
  sales_consultant_score              NUMERIC,
  purchase_process_score              NUMERIC,
  vehicle_delivery_score              NUMERIC,
  service_return_cnt                  NUMERIC,
  service_sat_score                   NUMERIC,
  service_appt_dropoff_score          NUMERIC,
  service_rep_score                   NUMERIC,
  service_facility_score              NUMERIC,
  vehicle_pickup_process_score        NUMERIC,
  service_quality_score               NUMERIC,
  frft_return_cnt                     NUMERIC,
  frft_pct_yes_score                  NUMERIC,
  frft_pct_routine_maint_yes_score    NUMERIC,
  frft_pct_warranty_yes_score         NUMERIC,

  part_sales                          NUMERIC,
  part_sales_obj                      NUMERIC,
  pct_part_sales_to_obj               NUMERIC,
  sales_rate                          NUMERIC,
  projected_sales                     NUMERIC,
  pct_proj_vs_obj                     NUMERIC,
  port_sales                          NUMERIC,
  port_pnvw                           NUMERIC,
  port_obj                            NUMERIC,
  port_obj_pct                        NUMERIC,
  whs_sales                           NUMERIC,
  whs_pnvw                            NUMERIC,
  whs_obj                             NUMERIC,
  whs_obj_pct                         NUMERIC,
  total_sales                         NUMERIC,
  total_veh                           NUMERIC,
  pnvw                                NUMERIC,
  total_obj                           NUMERIC,
  total_obj_pct                       NUMERIC,
  total_penetration_pct               NUMERIC,
  
  suggested_lines                      NUMERIC,
  accepted_lines                       NUMERIC,
  line_utilization_pct                 NUMERIC,
  suggested_part_no                    NUMERIC,
  override_part_no                     NUMERIC,
  parts_accepted_pct                   NUMERIC,
  net_utilization_pct                  NUMERIC,
  total_on_hand_value                  NUMERIC,
  suggested_on_hand_value              NUMERIC,
  suggested_inventory_pct              NUMERIC,
  overall_performance                  NUMERIC,
  overall_rating                       NUMERIC,
  total_partseye_stock_order_value     NUMERIC,
  total_supplemental_stock_order_value NUMERIC,
  total_emergency_order_value          NUMERIC,
  total_other_order_value              NUMERIC,
  partseye_stockorder_pct              NUMERIC,
  mechanical_off_shelf_fill_rate       NUMERIC,
  mechanical_pieces_sold               NUMERIC,
  mechanical_pieces_sold_from_shelf    NUMERIC,
  mechanical_emergency_orders          NUMERIC,
  mechanical_lost_sales                NUMERIC,
  net_off_shelf_fill_rate_pct          NUMERIC,
  total_off_shelf_fill_rate            NUMERIC,
  lost_sales_part_pct                  NUMERIC,
  lost_sales_total                     NUMERIC,
  total_demand                         NUMERIC,
  total_demand_per_employee_3          NUMERIC,
  total_suggestible_demand             NUMERIC,
  vehicle_sales                       NUMERIC,
  mechanical_sales                    NUMERIC,
  maintenance_sales                   NUMERIC,
  cpo_sales                           NUMERIC,
  total_sales_security                NUMERIC,
  mechanical_penetration_pct          NUMERIC,
  maintenance_penetration_pct         NUMERIC,
  cpo_penetration_pct                 NUMERIC,
  mech_cpo_pen_pct                    NUMERIC,
  mech_cpo_pen_pct_obj                NUMERIC,
  gp_puvr                             NUMERIC,
  op_new_veh                          NUMERIC,
  op_used_veh                         NUMERIC,
  op_service                          NUMERIC,
  op_pa_dep                           NUMERIC,
  op_body_shop                        NUMERIC,
  fixed_absorption                    NUMERIC,
  cust_effective_lr_subaru            NUMERIC,
  cust_effective_lr_other             NUMERIC,
  subaru_cust_labor_ro                NUMERIC,
  subaru_cust_labor_sls               NUMERIC,
  subaru_cust_labor_gp                NUMERIC,
  subaru_cust_labor_gp_pct            NUMERIC,
  subaru_warr_labor_ro                NUMERIC,
  subaru_warr_labor_sls               NUMERIC,
  subaru_warr_labor_gp                NUMERIC,
  subaru_warr_labor_gp_pct            NUMERIC,
  subaru_int_labor_ro                 NUMERIC,
  subaru_int_labor_sls                NUMERIC,
  subaru_int_labor_gp                 NUMERIC,
  subaru_int_labor_gp_pct             NUMERIC,
  subaru_prep_maint_ro                NUMERIC,
  subaru_prep_maint_sls               NUMERIC,
  subaru_prep_maint_gp                NUMERIC,
  subaru_prep_maint_gp_pct            NUMERIC,
  subaru_srv_labor_ro                 NUMERIC,
  subaru_srv_labor_sls                NUMERIC,
  subaru_srv_labor_gp                 NUMERIC,
  subaru_srv_labor_gp_pct             NUMERIC,
  subaru_expsrv_labor_ro              NUMERIC,
  subaru_expsrv_labor_sls             NUMERIC,
  subaru_expsrv_labor_gp              NUMERIC,
  subaru_expsrv_labor_gp_pct          NUMERIC,
  total_subaru_srv_labor_ro           NUMERIC,
  total_subaru_srv_labor_sls          NUMERIC,
  total_subaru_srv_labor_gp           NUMERIC,
  total_subaru_srv_labor_gp_pct       NUMERIC,
  subaru_parts_cust_mech_sls          NUMERIC,
  subaru_parts_cust_mech_gp           NUMERIC,
  subaru_parts_cust_mech_gp_pct       NUMERIC,
  subaru_parts_cust_body_sls          NUMERIC,
  subaru_parts_cust_body_gp           NUMERIC,
  subaru_parts_cust_body_gp_pct       NUMERIC,
  subaru_parts_warr_sls               NUMERIC,
  subaru_parts_warr_gp                NUMERIC,
  subaru_parts_warr_gp_pct            NUMERIC,
  subaru_counter_ct                   NUMERIC,
  subaru_counter_sls                  NUMERIC,
  subaru_counter_gp                   NUMERIC,
  subaru_counter_gp_pct               NUMERIC,
  subaru_wholesale_ct                 NUMERIC,
  subaru_wholesale_sls                NUMERIC,
  subaru_wholesale_gp                 NUMERIC,
  subaru_wholesale_gp_pct             NUMERIC,
  subaru_parts_prep_maint_sls         NUMERIC,
  subaru_parts_prep_maint_gp          NUMERIC,
  subaru_parts_prep_maint_gp_pct      NUMERIC,
  suba_pa_sls                         NUMERIC,
  suba_pa_gp                          NUMERIC,
  suba_pa_gp_pct                      NUMERIC,
  suba_pa_exp_sls                     NUMERIC,
  suba_pa_exp_gp                      NUMERIC,
  suba_pa_exp_gp_pct                  NUMERIC,
  tota_subaru_pa_sls                  NUMERIC,
  tota_subaru_pa_gp                   NUMERIC,
  tota_subaru_pa_gp_pct               NUMERIC,
  labor_per_ro_subaru                 NUMERIC,
  parts_labor_sales_ratio             NUMERIC
);



-- insert into new tables
insert into soa_deliver.fact_metrics
(select * from soa_deliver.fact_metrics_temp);

insert into soa_deliver.fact_metrics_agg_entity
(select * from soa_deliver.fact_metrics_agg_entity_temp);

insert into soa_deliver.fact_metrics_agg_district
(select * from soa_deliver.fact_metrics_agg_district_temp);

insert into soa_deliver.fact_metrics_agg_zone
(select * from soa_deliver.fact_metrics_agg_zone_temp);

insert into soa_deliver.fact_metrics_agg_region
(select * from soa_deliver.fact_metrics_agg_region_temp);

insert into soa_deliver.fact_metrics_agg_division
(select * from soa_deliver.fact_metrics_agg_division_temp);


COMMIT;
